name: smartlog-ai-mvp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - tk=8.6.14
  - pip:
      - pyaudio==0.2.14
      - vosk==0.3.44
      - pre-commit==3.3.3
      - pytest==7.4.3
      - openai-whisper==20240930
      - torch==2.2.2
      - numpy==1.24.3
      - tiktoken==0.9.0
      - black==24.3.0
      - flake8==6.0.0
      - bandit==1.7.5
      - rake-nltk==1.0.6
      - psutil==5.9.5
      - flake8-pyproject==1.2.3
      - pytest-mock==3.10.0
